version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  ngrok:
    image: wernight/ngrok
    env_file:
      - .env
    environment:
      - NGROK_PORT=api:5050
    ports:
      - "4040:4040" # ngrok web interface
